### ISSUE TITLE
Not supposrted for all PDFs

### ISSUE THREAD

**Issue by objectivecdeveloper** [brow/leaves#10]
The code works well with certain PDFs but not with all PDF.
Here is the list of errors which comes when parsing the PDF and resulting in to an empty white page.

Errors : 

FlateDecode: decoding error: incorrect header check.
invalid `Contents': not a stream or array.
missing or invalid arguments for color operator.
stack underflow: popping past mark.
font`F28' not found in document.
font `F168' not found in document.

Do any one has idea for this?

**Comment by brow** [comment]
The PDF example is intended only as an example, and is not tested with PDFs other than the one supplied. It sounds like this is problem either with your PDF file or with Core Graphics' PDF functions.
