### ISSUE TITLE
Pinch Zoom Issue - Two page viewing

### ISSUE THREAD

**Issue by objectivecdeveloper** [brow/leaves#11]
Hi all,

we face an issue which has been not reported yet.
We deployed the application in to iPhone , in portrait mode the zooming doesn't work properly.

Right page overlaps the left page , but in iPad the issue is not occurring.

Regards

**Comment by brow** [comment]
Since this issue concerns a fork, I'm closing it here. I suggest opening an issue against the fork you are using.
