### ISSUE TITLE
rendering pdf while zooming

### ISSUE THREAD

**Issue by matrog** [brow/leaves#13]
Is there a way to render pdf during zooming? my pdf lose quality while zooming. I tried CATiledView but the iOS crashes due to memory fault.

**Comment by aaronwardle** [comment]
Has anyone else managed to solve this? 

I have can zoom the view but it turns out all blurred.

**Comment by hammerlyrodrigo** [comment]
Not sure if it's too late now, but I created a stable CATiledLayer based approach here https://github.com/hammerlyrodrigo/leaves
