### ISSUE TITLE
too slow

### ISSUE THREAD

**Issue by lopes710** [brow/leaves#21]
I'm using rodrigo's leaves version and in iPad 5.0 it's too slow when changing the pages in landscape mode. Did anyone solve this? 

Thanks in advance

**Comment by lopes710** [comment]
The aaronwardle leaves version pages smoothly but when it zooms out it freezes and never returns to it's initial state. After that pages can't be turn.

**Comment by brow** [comment]
I'm closing this issue since it concerns a fork. There's some discussion of the fork's performance in #16.
