### ISSUE TITLE
ansani/Leaves project Landscape issue

### ISSUE THREAD

**Issue by kaushik4uwithlove** [brow/leaves#24]
Hi all,
I am working on leaves project for rendering images(applying page curl effect).I am successful in getting the page curl effect in Portrait Mode and unable to get two-page landscape view with two images side by side.could some one suggest me what should be done as landscape mode is locked when i rotate screen rotation.And also provide some sample project for getting two-page landscape view with images side by side.
Thanks for the assistance.

Regards,
kaushik

**Comment by brow** [comment]
Since this issue concerns a fork, I'm closing it here. I suggest opening an issue at @ansani's repo.
