### ISSUE TITLE
Is it possible to start from another pdf page other then the first?

### ISSUE THREAD

**Issue by Sror** [brow/leaves#25]
I would like the app to open in the middle of the order of pages. So if there were only 3 pages I would like it to open on 2nd. Any Ideas on the best way to do this?

Thanks!

**Comment by faizz** [comment]
I am interested in this as well.

**Comment by faizz** [comment]
Here is a solution to the problem
In PDFExampleViewController.m modify the following lines:

```
@synthesize startPageNumber;

- (id)initWithPageNumber:(NSUInteger)pageNumber {
if (self = [super init]) {
    CFURLRef pdfURL = CFBundleCopyResourceURL(CFBundleGetMainBundle(), CFSTR("lungResearchPaper2.pdf"), NULL, NULL);
    pdf = CGPDFDocumentCreateWithURL((CFURLRef)pdfURL);
    CFRelease(pdfURL);
    startPageNumber = pageNumber;
}
return self;
}
- (void) viewDidLoad {
[super viewDidLoad];
leavesView.backgroundRendering = YES;
leavesView.currentPageIndex = startPageNumber - 1;
[self displayPageNumber:startPageNumber];
}
```

**Comment by Sror** [comment]
Thanks, it's working good, but have problem to load pdf file (even changed name).

**Comment by brow** [comment]
It sounds like your question is answered, so I'm closing this issue.
