### ISSUE TITLE
Retina Display Support

### ISSUE THREAD

**Issue by Vortec4800** [brow/leaves#3]
It looks like the contexts used in the cache only support a scale of 1.0 - I've been trying to set it to 2.0 when on the iPhone 4 but to no avail. I'm doing pretty standard drawing in the CGContextRef, but it doesn't seem to scale on its own. Is there something else I need to do, perhaps to some of the layers in Leaves?

**Comment by Vortec4800** [comment]
Just thought I would mention that I poked around some more and fixed the issue, so Leaves now supports the Retina display using normal drawing functions. Nothing special needs to be done to get the higher resolution display. Though because the scale property doesn't exist in 3.2, it isn't compatible with the iPad until 4.2 is available.

For anyone that's interested, you can find the Retina display support in a Fork I made:
http://github.com/Vortec4800/leaves

**Comment by brow** [comment]
Belated thanks for your work. I added a link to your fork in the README for posterity.
