### ISSUE TITLE
Could not run Sample Project

### ISSUE THREAD

**Issue by ghousesgb** [brow/leaves#30]
![leaves_error](https://f.cloud.github.com/assets/1427049/1304302/31455c82-317b-11e3-8960-2bfd84e24a70.png)

Hi,
I could not able to run your sample project and even, i tried to build new project by added leaves folder and adding QuartzCore.framework. I have attached image,

thanks

**Comment by akasteven** [comment]
just import QuartzCore/QuartzCore.h

**Comment by brow** [comment]
Yes, it looks like the Core Animation headers aren't being imported. However, I'm not seeing this issue in Xcode 5. What happens if you use the current version of Xcode?
