### ISSUE TITLE
context error on iOS 4.2

### ISSUE THREAD

**Issue by arodeus** [brow/leaves#6]
Hi! I'm debugging my application on iOS 4.2 GM seed, and I obtain the following error on the simulator console:

<Error>: CGContextClipToRect: invalid context 0x0
<Error>: CGContextGetClipBoundingBox: invalid context 0x0
<Error>: CGContextConcatCTM: invalid context 0x0
<Error>: CGContextDrawImage: invalid context 0x0
<Error>: CGBitmapContextCreateImage: invalid context 0x0
<Error>: CGContextClipToRect: invalid context 0x0
<Error>: CGContextGetClipBoundingBox: invalid context 0x0
<Error>: CGContextConcatCTM: invalid context 0x0
<Error>: CGContextDrawImage: invalid context 0x0
<Error>: CGBitmapContextCreateImage: invalid context 0x0

Error seems issued by LeavesCache.m on the following member function
- (CGImageRef) imageForPageIndex:(NSUInteger)pageIndex

I just start to debug the application, so these are just my first impressions.

Hope to a fix soon, or maybe an hint to fix the so problem so I'll be able to commit the fix.

Thx,
Diego

**Comment by arodeus** [comment]
SOLVED!

Preface:
I load a LeavesController subclass as Modal View as Full Screen.

Why the error:
Using iOS 4.2, load the subclass as modal view seems generate a double time call for (CGImageRef) imageForPageIndex:(NSUInteger)pageIndex (in LeavesCache.m) , generating a NULL when CGBitmapContextCreate is called.

Solution:
I added the following code, return nil if CGBitmapContextCreate return NULL

if (context == nil) return nil;

**Comment by VegetarianZombie** [comment]
Almost a year later ... thanks for debugging this issue.

**Comment by Jasmeet22** [comment]
iDidn't get the desired answer

**Comment by Jasmeet22** [comment]
ok i got it thanx
