### ISSUE TITLE
when i try a different PDF file and load it to iPad... it got..

### ISSUE THREAD

**Issue by ghost** [brow/leaves#7]
**\* _NSAutoreleaseNoPool(): Object 0x126460 of class NSCFData autoreleased with no pool in place - just leaking
Stack: XXXX...XX

the main.m is same as general. Only thing i do is try another PDF with 133 page and load it to my iPad. Anyone got the same problem..?

**Comment by arodeus** [comment]
usually this error is related to a thread with no autorelease pool defined. Are you loading the PDF using a different thread instead of the main one?

**Comment by ghost** [comment]
after i use iOS4.2, the problem solved.
