### ISSUE TITLE
Zoom in and Rotate the device and then double tap

### ISSUE THREAD

**Issue by uptscs** [brow/leaves#9]
When I zoom in the pdf and then rotate to landscape to portrait or portrait to landscpae and the double tap to go to the actual size of the PDF, it shows the blank white space in the PDF.
Please let me know if I can fix this issue.

Thanks,
UPT

**Comment by objectivecdeveloper** [comment]
Hi UPT,
   Just solved the issue, just stop the orientaion changes when the page is zoomed in or zoomed out. I am also updating the fork. Please take the code for reference.

Thanks & Regards,
Nishant Shah

**Comment by uptscs** [comment]
Thanks Nishant.
